name: 'StackGen: Drift Detection'
description: 'Trigger infrastructure drift detection for an AppStack using StackGen'

inputs:
  appstack_id:
    description: 'The StackGen AppStack ID'
    required: true
  region:
    description: 'Cloud region (e.g., us-east-1)'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - drift
    - detect
    - --appstack-id
    - ${{ inputs.appstack_id }}
    - --var=region=${{ inputs.region }}