name: Drift Detection

on:
  workflow_dispatch:

jobs:
  drift:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger StackGen Drift Detection
        uses: AaravAggarwal/stackgen-drift-detection-action@main
        env:
          STACKGEN_TOKEN: ${{ secrets.STACKGEN_TOKEN }}
        with:
          appstack_id: 'app-stack-12345'
          region: 'us-east-1'
